name: FinOps Cost Guardrail
on: [push, pull_request]

jobs:
  infracost:
    name: Infracost Analysis
    runs-on: ubuntu-latest
    # Node.js 24 fix for 2026
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Setup Infracost
        uses: infracost/actions/setup@v3 # Updated to v3
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Generate Cost Breakdown
        run: |
          infracost breakdown --path . \
                            --format json \
                            --out-file /tmp/infracost.json

      - name: Show Cost Table in Terminal
        run: |
          infracost output --path /tmp/infracost.json --format table
